name: Deploy Website with CDK

on:
  push:
    branches: [ main, master ]
    paths:
      - 'infra/**'
      - 'website/**'
      - '.github/workflows/deploy.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js for website build
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and build website
        working-directory: website
        run: |
          npm ci
          npm run build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Install CDK deps (Python)
        working-directory: infra_py
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy with CDK (Python)
        working-directory: infra_py
        run: |
          source .venv/bin/activate
          cdk deploy --require-approval never


